// =============================================================================
// tb_eth_parser.sv - Testbench for Ethernet Frame Parser
// =============================================================================
// Reads packets from hex file generated by gen_packets.py,
// feeds them byte-by-byte into the Ethernet parser, and verifies
// that the output matches expected IP payload.
// =============================================================================

`timescale 1ns / 1ps

module tb_eth_parser;

    // =========================================================================
    // Parameters
    // =========================================================================
    localparam CLK_PERIOD = 5;  // 200 MHz
    localparam MAX_PACKET_BYTES = 2048;
    localparam MAX_PACKETS = 200;

    // =========================================================================
    // Signals
    // =========================================================================
    logic        clk;
    logic        rst_n;

    // AXI-Stream Input
    logic [7:0]  s_axis_tdata;
    logic        s_axis_tvalid;
    logic        s_axis_tready;
    logic        s_axis_tlast;

    // AXI-Stream Output
    logic [7:0]  m_axis_tdata;
    logic        m_axis_tvalid;
    logic        m_axis_tready;
    logic        m_axis_tlast;

    // Status
    logic        frame_dropped;
    logic        frame_accepted;

    // =========================================================================
    // DUT Instantiation
    // =========================================================================
    eth_parser dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .s_axis_tdata   (s_axis_tdata),
        .s_axis_tvalid  (s_axis_tvalid),
        .s_axis_tready  (s_axis_tready),
        .s_axis_tlast   (s_axis_tlast),
        .m_axis_tdata   (m_axis_tdata),
        .m_axis_tvalid  (m_axis_tvalid),
        .m_axis_tready  (m_axis_tready),
        .m_axis_tlast   (m_axis_tlast),
        .frame_dropped  (frame_dropped),
        .frame_accepted (frame_accepted)
    );

    // =========================================================================
    // Clock Generation
    // =========================================================================
    initial clk = 0;
    always #(CLK_PERIOD / 2.0) clk = ~clk;

    // =========================================================================
    // Packet Storage
    // =========================================================================
    logic [7:0] packet_mem [0:65535];  // Raw hex file data
    int         mem_size;

    // =========================================================================
    // Test Counters
    // =========================================================================
    int packets_sent = 0;
    int packets_received = 0;
    int packets_dropped = 0;
    int total_bytes_out = 0;
    int errors = 0;

    // =========================================================================
    // Output Capture
    // =========================================================================
    logic [7:0] output_bytes [0:MAX_PACKET_BYTES-1];
    int         output_byte_cnt;

    // =========================================================================
    // Load Hex File
    // =========================================================================
    initial begin
        $readmemh("sim/test_data/packets.hex", packet_mem);
        // Count entries (find the 00 00 terminator)
        mem_size = 0;
        // We'll just set a large value and let the logic handle termination
        mem_size = 65536;
    end

    // =========================================================================
    // Main Test Sequence
    // =========================================================================
    initial begin
        // Initialize
        rst_n          = 0;
        s_axis_tdata   = 0;
        s_axis_tvalid  = 0;
        s_axis_tlast   = 0;
        m_axis_tready  = 1;  // Always ready to accept output

        // Reset
        repeat (10) @(posedge clk);
        rst_n = 1;
        repeat (5) @(posedge clk);

        $display("=========================================");
        $display("  Ethernet Parser Testbench");
        $display("=========================================");

        // Read packets from memory and feed them in
        fork
            feed_packets();
            capture_output();
            monitor_status();
        join_any

        // Wait for pipeline to drain
        repeat (100) @(posedge clk);

        // Report
        $display("");
        $display("=========================================");
        $display("  Test Results");
        $display("=========================================");
        $display("  Packets sent:     %0d", packets_sent);
        $display("  Packets received: %0d", packets_received);
        $display("  Packets dropped:  %0d", packets_dropped);
        $display("  Total bytes out:  %0d", total_bytes_out);
        $display("  Errors:           %0d", errors);
        $display("=========================================");

        if (errors == 0)
            $display("  *** ALL TESTS PASSED ***");
        else
            $display("  *** %0d ERRORS DETECTED ***", errors);

        $finish;
    end

    // =========================================================================
    // Task: Feed packets from hex memory
    // =========================================================================
    task automatic feed_packets();
        int mem_idx;
        int pkt_len;
        int byte_idx;

        mem_idx = 0;

        while (1) begin
            // Read 2-byte length prefix
            pkt_len = {packet_mem[mem_idx], packet_mem[mem_idx + 1]};
            mem_idx += 2;

            // Check for end marker
            if (pkt_len == 0) begin
                $display("[FEED] All packets sent.");
                break;
            end

            $display("[FEED] Sending packet %0d (%0d bytes)", packets_sent, pkt_len);

            // Send packet bytes one by one
            for (byte_idx = 0; byte_idx < pkt_len; byte_idx++) begin
                @(posedge clk);
                s_axis_tdata  <= packet_mem[mem_idx + byte_idx];
                s_axis_tvalid <= 1'b1;
                s_axis_tlast  <= (byte_idx == pkt_len - 1);

                // Wait for handshake
                @(posedge clk);
                while (!s_axis_tready) @(posedge clk);
            end

            // Deassert valid after packet
            @(posedge clk);
            s_axis_tvalid <= 1'b0;
            s_axis_tlast  <= 1'b0;

            mem_idx += pkt_len;
            packets_sent++;

            // Small gap between packets
            repeat (3) @(posedge clk);
        end
    endtask

    // =========================================================================
    // Task: Capture output bytes
    // =========================================================================
    task automatic capture_output();
        forever begin
            @(posedge clk);
            if (m_axis_tvalid && m_axis_tready) begin
                total_bytes_out++;
                if (m_axis_tlast) begin
                    packets_received++;
                end
            end
        end
    endtask

    // =========================================================================
    // Task: Monitor status signals
    // =========================================================================
    task automatic monitor_status();
        forever begin
            @(posedge clk);
            if (frame_dropped) begin
                packets_dropped++;
                $display("[STATUS] Frame DROPPED (packet %0d)", packets_sent - 1);
            end
            if (frame_accepted) begin
                $display("[STATUS] Frame ACCEPTED (packet %0d)", packets_sent);
            end
        end
    endtask

    // =========================================================================
    // Timeout Watchdog
    // =========================================================================
    initial begin
        #(CLK_PERIOD * 500000);
        $display("ERROR: Testbench timed out!");
        $finish;
    end

endmodule
